### ISSUE TITLE
Team kodi issue? xbmc/xbmc/

### ISSUE THREAD

**Issue by I-Cat** [I-Cat-org/x-1#1]
Issue test 2

**Comment by easyaspi314** [comment]
*Gee, thanks* :joy:

**Comment by I-Cat** [comment]
Ping @easyaspi314 
Ping @I-Cat-org/team-i-cat

**Comment by I-Cat** [comment]
> _Gee, thanks_ 😂

Ha ha I really am stuck Maybe Start over?

**Comment by I-Cat** [comment]
> _Gee, thanks_ 😂

O Wow Look at all your repos wow im a small fry.
I am really happy to see you, and besides now You have an Offical Badge under your name yey!

mention: @easyaspi314

**Comment by I-Cat** [comment]
@Vasyl Gello @basilgello
Help Wanted

**Comment by basilgello** [comment]
> @Vasyl Gello @basilgello
> Help Wanted

ah? :)

**Comment by I-Cat** [comment]
> > @Vasyl Gello @basilgello
> > Help Wanted
> 
> ah? :)

Mention: @basilgello basilgello
Yes plz help me I think somethings wrong.

**Comment by basilgello** [comment]
I dont understand the problem...

**Comment by I-Cat** [comment]
> I dont understand the problem... But I accepted an invitation 👍

Okay tnx

**Comment by lrusak** [comment]
You cannot access https://github.com/xbmc/xbmc because we have blocked you from the xbmc organization. 

This is due to multiple negative interactions with you and many Team Kodi members. You have been consistently harassing people with nonsensical issues and pull requests.

If you would like to learn how to contribute successfully to open source projects you shouldn't make yourself look like a bot. You have multiple github organization accounts with multiple cloned repositories. You make commits and pull requests with zero context and value.

I would suggest joining #kodi on freenode IRC if you would like to chat with developers directly about how to improve your behaviour.

Until your behavior improves you will continue to be blocked.

**Comment by I-Cat** [comment]
@ Vasyl Gello basilgello
@ easyaspi314 (Devin) easyaspi314

I will need to close this and close this branch bc I did it Wrong.
